version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:3000/api}
        - VITE_WS_URL=${VITE_WS_URL:-http://localhost:3000}
        - VITE_NODE_ENV=production
    container_name: convo-frontend
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      - NODE_ENV=production

networks:
  default:
    name: convo-network