apiVersion: v1
kind: Namespace
metadata:
  name: convochat
  labels:
    name: convochat
    environment: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: convochat-frontend-sa
  namespace: convochat
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: convochat
  name: convochat-frontend-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: convochat-frontend-binding
  namespace: convochat
subjects:
- kind: ServiceAccount
  name: convochat-frontend-sa
  namespace: convochat
roleRef:
  kind: Role
  name: convochat-frontend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: convochat-frontend-netpol
  namespace: convochat
spec:
  podSelector:
    matchLabels:
      app: convochat-frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: nginx-ingress
    - podSelector:
        matchLabels:
          app: nginx-ingress
    ports:
    - protocol: TCP
      port: 8080
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          name: convochat
    - podSelector:
        matchLabels:
          app: convochat-backend
    ports:
    - protocol: TCP
      port: 3000
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80